In [46]:
import pandas as pd

data = {
    "id_venta":        [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "vendedor":        ["Ana","Luis","Ana","Pedro","Luis","Ana","Pedro","Luis","Ana","Pedro","Luis","Ana","Pedro","Ana","Luis"],
    "categoria":       ["Móviles","Accesorios","Portátiles","Móviles","Accesorios","Portátiles","Móviles","Accesorios","Portátiles","Móviles","Accesorios","Portátiles","Móviles","Accesorios","Portátiles"],
    "cantidad":        [2,5,1,3,4,1,2,6,1,1,3,2,4,5,1],
    "precio_unitario": [699,29,1199,649,19,1099,679,24,1249,659,22,1150,689,27,1099],
    "descuento":       [0,0.1,0,0.05,0,0.15,0,0.1,0,0.05,0,0,0.1,0,0.05]
}

In [47]:
df = pd.DataFrame(data)

**CARGA**

In [48]:
print("-----------------------------------------")
print("El numero de rows (entries) seguido del numero de colummns del dataset: \n")
print(df.shape)
print("-----------------------------------------")
print("Su ocupación en memoria: \n")
df.info()
print("-----------------------------------------")
print("Representación de las columnas: \n")
print(df.head())
print("-----------------------------------------")

-----------------------------------------
El numero de rows (entries) seguido del numero de colummns del dataset:

(15, 6)
-----------------------------------------
Su ocupación en memoria:

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         15 non-null     int64
 1   vendedor         15 non-null     str
 2   categoria        15 non-null     str
 3   cantidad         15 non-null     int64
 4   precio_unitario  15 non-null     int64
 5   descuento        15 non-null     float64
dtypes: float64(1), int64(3), str(2)
memory usage: 852.0 bytes
-----------------------------------------
Representación de las columnas:

   id_venta vendedor   categoria  cantidad  precio_unitario  descuento
0         1      Ana     Móviles         2              699       0.00
1         2     Luis  Accesorios         5               29       0.10
2         3      Ana  Portátiles         1             1199       0.00
3         4    Pedro     Móviles         3              649       0.05
4         5     Luis  Accesorios         4               19       0.00
-----------------------------------------

**ESTRUCURA**

In [49]:
print("-----------------------------------------")
print("Que tipo de valor es en cada columna: ")
print(df.dtypes)
print("-----------------------------------------")
print("Valores que se repiten en cada columna.")
print("____________________________")
print("Vendedores que se repiten: ")
print(df["vendedor"].value_counts())
print("____________________________")
print("Categorias que se repiten: ")
print(df["categoria"].value_counts())
print("____________________________")
print("Precios que se repiten: ")
print(df["precio_unitario"].value_counts())
print("____________________________")
print("-----------------------------------------")

-----------------------------------------
Que tipo de valor es en cada columna:
id_venta             int64
vendedor               str
categoria              str
cantidad             int64
precio_unitario      int64
descuento          float64
dtype: object
-----------------------------------------
Valores que se repiten en cada columna.
____________________________
Vendedores que se repiten:
vendedor
Ana      6
Luis     5
Pedro    4
Name: count, dtype: int64
____________________________
Categorias que se repiten:
categoria
Móviles       5
Accesorios    5
Portátiles    5
Name: count, dtype: int64
____________________________
Precios que se repiten:
precio_unitario
1099    2
699     1
29      1
1199    1
649     1
19      1
679     1
24      1
1249    1
659     1
22      1
1150    1
689     1
27      1
Name: count, dtype: int64
____________________________
-----------------------------------------

**1 - La categoría que mas genera ingresos**

In [50]:
# 1 calcular el ingreso de cadafila (cada venta) y mostrar la nueva columna
# Para calcular el ingreso real por fila se multiplica cantidad × precio
# esto genera una columna nueva en el df, una por cada venta
df['ingreso'] = df['cantidad'] * df['precio_unitario']
print("-----------------------------------------")
print("Ingreso por cada venta: ")
print(df['ingreso'])
print("-----------------------------------------")

# 1.1 Sacar la agrupación por columna
# Groupby agrupa todas las filas que comparten la misma categoría
# sum() porque la pregunta pide el total de dinero por grupo, no contar filas
# sort_values(ascending=False) para que el mayor quede primero

print("Monto por categoría: ")
ingresos_categoria = df.groupby('categoria')['ingreso'].sum().sort_values(ascending=False)
print(ingresos_categoria)
print("-----------------------------------------")

# 1.2 Exreaer de una operación/dataframe/objeto el valor maximo por indice
# idxmax() devuelve el nombre del índice con el valor más alto
# se necesita el nombre de la categoría, no el número en sí
print("Categoría mas vendida: ")
categoria_mas_vendida = ingresos_categoria.idxmax()
print(categoria_mas_vendida)
print("-----------------------------------------")

-----------------------------------------
Ingreso por cada venta:
0     1398
1      145
2     1199
3     1947
4       76
5     1099
6     1358
7      144
8     1249
9      659
10      66
11    2300
12    2756
13     135
14    1099
Name: ingreso, dtype: int64
-----------------------------------------
Monto por categoría:
categoria
Móviles       8118
Portátiles    6946
Accesorios     566
Name: ingreso, dtype: int64
-----------------------------------------
Categoría mas vendida:
Móviles
-----------------------------------------

**2 - Número de ventas por persona**

In [51]:
df.head()

,id_venta,vendedor,categoria,cantidad,precio_unitario,descuento,ingreso
0,1,Ana,Móviles,2,699,0.00,1398
1,2,Luis,Accesorios,5,29,0.10,145
2,3,Ana,Portátiles,1,1199,0.00,1199
3,4,Pedro,Móviles,3,649,0.05,1947
4,5,Luis,Accesorios,4,19,0.00,76

In [52]:
# 2 Numero de ventas poe vendedor
# 2.1 Hacer un objeto que lleva una condición
# filtrar solo las filas donde hubo descuento, df[condición] deja solo las filas True
ventas_descuento = df[df['descuento']>0]

# 2.2 Agrupar por numero de veces que se realiza algo
# groupby por vendedor para agrupar sus transacciones
# count() sobre id_venta porque la pregunta pide cuántas ventas hizo cada uno
# se usa count() y no sum() porque se busca el número de operaciones, no el dinero total
venta_por_vendedor = ventas_descuento.groupby('vendedor')['id_venta'].count()
print("-----------------------------------------")
print("Ventas que ha realizado cada vendedor: ")
print(venta_por_vendedor)
print("-----------------------------------------")

-----------------------------------------
Ventas que ha realizado cada vendedor:
vendedor
Ana      1
Luis     3
Pedro    3
Name: id_venta, dtype: int64
-----------------------------------------

**3 - Ticket medio**

In [53]:
df.head()

,id_venta,vendedor,categoria,cantidad,precio_unitario,descuento,ingreso
0,1,Ana,Móviles,2,699,0.00,1398
1,2,Luis,Accesorios,5,29,0.10,145
2,3,Ana,Portátiles,1,1199,0.00,1199
3,4,Pedro,Móviles,3,649,0.05,1947
4,5,Luis,Accesorios,4,19,0.00,76

In [55]:
# 3 Conteo de filas por columna
# 3.1 contar cuántas ventas (filas) hubo por categoría
ventas_por_categoria = df.groupby('categoria')['id_venta'].count()

# 3.2 División entre objetos para sacar la media 
# dividir los dos groupby — pandas alinea por nombre de categoría solo
ticket_medio = ingresos_categoria / ventas_por_categoria
ticket_medio_ordenado = ticket_medio.sort_values(ascending=False)

print("-----------------------------------------")
print("Ticket medio por categoría:")
print(ticket_medio_ordenado)
print("-----------------------------------------")

-----------------------------------------
Ticket medio por categoría:
categoria
Móviles       1623.6
Portátiles    1389.2
Accesorios     113.2
dtype: float64
-----------------------------------------