In [3]:
from pathlib import Path
import pandas as pd

def find_project_root():
    current = Path.cwd()
    for parent in [current] + list(current.parents):
        if (parent / '.git').exists() or (parent / 'data').exists():
            return parent
    return current

PROJECT_ROOT = find_project_root()
DATA_EXTERNAL = PROJECT_ROOT / 'data' / 'external'

print(f"Check: Proyecto raíz: {PROJECT_ROOT}")
print(f"Check: Datos external: {DATA_EXTERNAL}")

df = pd.read_csv(DATA_EXTERNAL / 'FruitVegetalPrices.csv' )

Check: Proyecto raíz: c:\Users\alefe\OneDrive\Documentos\GitHub\data-analytics-project
Check: Datos external: c:\Users\alefe\OneDrive\Documentos\GitHub\data-analytics-project\data\external

## Paso 1 - Carga

Lo primero a analizar dentro de un Dataset no son sus datos, ni su estructura. Lo más inmediato es comprobar si es coherente con lo designado.

1. **Shape** - Saber cuantas filas y cuantas columnas
2. **Memoria** - cual es su peso en MB
3. **Head** - Confirmación de carga y saber sus primeras filas

In [4]:
# 1 - una simple consulta de cuantas filas y columnas en el orden dicho
df.shape

(62, 8)

In [5]:
# 2 - Saber que ocupa en el equipo
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fruit               62 non-null     str
 1   Form                62 non-null     str
 2   RetailPrice         62 non-null     float64
 3   RetailPriceUnit     62 non-null     str
 4   Yield               62 non-null     float64
 5   CupEquivalentSize   62 non-null     float64
 6   CupEquivalentUnit   62 non-null     str
 7   CupEquivalentPrice  62 non-null     float64
dtypes: float64(4), str(4)
memory usage: 4.0 KB

In [6]:
# 3 -  confirmar el cargado y saber que columnas y primeras filas existen
df.head()

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Apples,Fresh,1.5193,per pound,0.90,0.2425,pounds,0.4094
1,"Apples, applesauce",Canned,1.0660,per pound,1.00,0.5401,pounds,0.5758
2,"Apples, ready-to-drink",Juice,0.7804,per pint,1.00,8.0000,fluid ounces,0.3902
3,"Apples, frozen concentrate",Juice,0.5853,per pint,1.00,8.0000,fluid ounces,0.2926
4,Apricots,Fresh,2.9665,per pound,0.93,0.3638,pounds,1.1603

### Una ejecución que puede cubir facilmente las necesidades de una carga:

In [7]:
print("Dimensiones")
print(df.shape)
print("\nInformación - Memoria")
df.info()
print("\nColumnas y primeras filas")
print(df.head())

Dimensiones
(62, 8)

Información - Memoria
<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fruit               62 non-null     str
 1   Form                62 non-null     str
 2   RetailPrice         62 non-null     float64
 3   RetailPriceUnit     62 non-null     str
 4   Yield               62 non-null     float64
 5   CupEquivalentSize   62 non-null     float64
 6   CupEquivalentUnit   62 non-null     str
 7   CupEquivalentPrice  62 non-null     float64
dtypes: float64(4), str(4)
memory usage: 4.0 KB

Columnas y primeras filas
                        Fruit    Form  RetailPrice RetailPriceUnit  Yield  \
0                      Apples   Fresh       1.5193       per pound   0.90
1          Apples, applesauce  Canned       1.0660       per pound   1.00
2      Apples, ready-to-drink   Juice       0.7804        per pint   1.00
3  Apples, frozen concentrate   Juice       0.5853        per pint   1.00
4                    Apricots   Fresh       2.9665       per pound   0.93

   CupEquivalentSize CupEquivalentUnit  CupEquivalentPrice
0             0.2425            pounds              0.4094
1             0.5401            pounds              0.5758
2             8.0000      fluid ounces              0.3902
3             8.0000      fluid ounces              0.2926
4             0.3638            pounds              1.1603

## Paso 2 - Estructura

Cuantos valores únicos existen en las columnas de texto

1. **dtypes** - para ver los tipos de cada columna
2. **Para cada columna de texto que aparezca categórica**, value_counts() - empieza por From y RetailPriceUnit

In [8]:
# 1 el dtypes es un atributo entonces su información dentro del Dataset es recursiva ya es predefinida.
# Debe mostrar exactamente a que tipo de dato es cada columna
print(df.dtypes)

Fruit                     str
Form                      str
RetailPrice           float64
RetailPriceUnit           str
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit         str
CupEquivalentPrice    float64
dtype: object

In [9]:
 #2 Se accede a una sola columna con el df.['NombreColumna']
print(df['Form'].value_counts())
print()
#2.1 el .value_counts() es un método que cuenta cuantas veces aparece cada valor único 
# dentro de cada columna
print(df['Form'])
print()
print(df['RetailPriceUnit'].value_counts())
print()
print(df['CupEquivalentUnit'].value_counts())

Form
Fresh     24
Canned    12
Juice     11
Dried      9
Frozen     6
Name: count, dtype: int64

0      Fresh
1     Canned
2      Juice
3      Juice
4      Fresh
       ...
57     Fresh
58    Frozen
59     Fresh
60    Frozen
61     Fresh
Name: Form, Length: 62, dtype: str

RetailPriceUnit
per pound    51
per pint     11
Name: count, dtype: int64

CupEquivalentUnit
pounds          51
fluid ounces    11
Name: count, dtype: int64

## Ejecución en un paso que abarca todo el tema de estructura en dataset

In [13]:
print("Tipos de datos por columna: ")
print(df.dtypes)
print()
print("Número de productos por 'forma' de la fruta: ")
print(df['Form'].value_counts())
print()
print("Cantidad por unidad de peso:")
print(df['RetailPriceUnit'].value_counts())
print()
print("Cantidad por estado (sólido líquido)")
print(df['CupEquivalentUnit'].value_counts())

Tipos de datos por columna:
Fruit                     str
Form                      str
RetailPrice           float64
RetailPriceUnit           str
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit         str
CupEquivalentPrice    float64
dtype: object

Número de productos por 'forma' de la fruta:
Form
Fresh     24
Canned    12
Juice     11
Dried      9
Frozen     6
Name: count, dtype: int64

Cantidad por unidad de peso:
RetailPriceUnit
per pound    51
per pint     11
Name: count, dtype: int64

Cantidad por estado (sólido líquido)
CupEquivalentUnit
pounds          51
fluid ounces    11
Name: count, dtype: int64

## Paso 3 - Calidad

Internalizar. Tener en cuenta si existen datos nulos, filas repetidas y combinaciones repetidas.

1. **¿falta algún dato?**
2. **¿hay filas repetidas?**

In [14]:
# 1 Filas repetidas
df.isnull()

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
57,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False