In [7]:
import pandas as pd

In [8]:
from pathlib import Path

# 1. Directorio actual (donde ejecutas el notebook)
current = Path.cwd()

# 2. Subir hasta la raíz del proyecto
PROJECT_ROOT = current.parent.parent

# 3. Ruta a los datos
DATA_PATH = PROJECT_ROOT / 'data' / 'raw'

# 4. Nombre del archivo (corregido)
CSV_FILE_NAME = 'wheat_coffee_corn_prizes.csv'

# 5. Ruta completa al archivo
CSV_FILE_PATH = DATA_PATH / CSV_FILE_NAME

In [9]:
pf = pd.read_csv(CSV_FILE_PATH)
pf

          Date    Wheat    Coffe     Corn
0    8/20/1973    5.085   0.6735    3.115
1    8/21/1973    5.285      NaN    3.015
2    8/22/1973      NaN    0.658    2.915
3    8/23/1973    5.005   0.6675      NaN
4    8/24/1973     5.18    0.666      2.9
5    8/27/1973      NaN    0.659      2.8
6    8/28/1973    4.889      NaN   2.6785
7    8/29/1973    5.056   0.6345  missing
8    8/30/1973      NaN   0.6387    2.509
9    8/31/1973    4.974      NaN   2.5035
10    9/4/1973    4.775   0.6432    2.405
11    9/5/1973    4.575    0.637      NaN
12    9/6/1973      NaN      NaN      NaN
13    9/7/1973    4.945    0.638     2.47
14   9/10/1973    4.985   0.6335     2.44
15   9/10/1973    4.985   0.6335     2.44
16   9/11/1973      NaN   0.6302   2.4875
17   9/12/1973    4.985      NaN   2.3875
18   9/13/1973    5.085    0.645      NaN
19   9/14/1973      NaN   0.6645   2,4975
20   9/15/1973     5.30      NaN    2.500
21   9/16/1973       50    0.700      NaN
22   9/17/1973      NaN      6.5   2.5975
23   9/18/1973    5.16    0.6562   2.4975
24   9/19/1973     5.31  missing    2.495
25   9/20/1973      NaN      NaN      2.5
26  1973-09-21     5.07   0.6465      NaN
27   9/22/1973     5.12      NaN     2.55
28   9/23/1973      NaN    0.652     2.58
29   9/24/1973     5.09   0.6485     2.57
30   9/25/1973      NaN      NaN      NaN
31   9/26/1973     5.13      NaN      2.6
32   9/27/1973      NaN    0.647      NaN
33   9/28/1973      5.1    0.653     2.61
34   9/29/1973      NaN      NaN      NaN
35   9/30/1973      5.2      NaN     2.65
36   10/1/1973      NaN    0.658     2.63
37   10/2/1973     5.16    0.657      NaN
38   10/3/1973  missing    0.656     2.61
39   10/4/1973     5.17      NaN     2.64
40   10/5/1973      NaN    0.661      NaN
41   10/6/1973     5.21    0.662      NaN
42   10/7/1973      NaN      NaN      NaN
43   10/8/1973     5.23    0.664     2.69
44   10/9/1973     5.24      NaN      2.7
45  10/10/1973     5.25    0.666     2.71
46  10/11/1973      NaN    0.667     2.72
47  10/12/1973     5.27      NaN     2.73
48  10/13/1973      NaN    0.669     2.74
49  10/14/1973     5.29     0.67      NaN
50  10/15/1973      NaN    0.671     2.76
51  10/16/1973     5.31      NaN     2.77
52  10/17/1973     5.32    0.673      NaN
53  10/18/1973      NaN    0.674     2.79

In [10]:
pf.tail(20)

          Date    Wheat  Coffe  Corn
34   9/29/1973      NaN    NaN   NaN
35   9/30/1973      5.2    NaN  2.65
36   10/1/1973      NaN  0.658  2.63
37   10/2/1973     5.16  0.657   NaN
38   10/3/1973  missing  0.656  2.61
39   10/4/1973     5.17    NaN  2.64
40   10/5/1973      NaN  0.661   NaN
41   10/6/1973     5.21  0.662   NaN
42   10/7/1973      NaN    NaN   NaN
43   10/8/1973     5.23  0.664  2.69
44   10/9/1973     5.24    NaN   2.7
45  10/10/1973     5.25  0.666  2.71
46  10/11/1973      NaN  0.667  2.72
47  10/12/1973     5.27    NaN  2.73
48  10/13/1973      NaN  0.669  2.74
49  10/14/1973     5.29   0.67   NaN
50  10/15/1973      NaN  0.671  2.76
51  10/16/1973     5.31    NaN  2.77
52  10/17/1973     5.32  0.673   NaN
53  10/18/1973      NaN  0.674  2.79

In [11]:
pf.columns

Index(['Date', 'Wheat', 'Coffe', 'Corn'], dtype='str')

In [12]:
pf.shape

(54, 4)

In [13]:
pf.info

<bound method DataFrame.info of           Date    Wheat    Coffe     Corn
0    8/20/1973    5.085   0.6735    3.115
1    8/21/1973    5.285      NaN    3.015
2    8/22/1973      NaN    0.658    2.915
3    8/23/1973    5.005   0.6675      NaN
4    8/24/1973     5.18    0.666      2.9
5    8/27/1973      NaN    0.659      2.8
6    8/28/1973    4.889      NaN   2.6785
7    8/29/1973    5.056   0.6345  missing
8    8/30/1973      NaN   0.6387    2.509
9    8/31/1973    4.974      NaN   2.5035
10    9/4/1973    4.775   0.6432    2.405
11    9/5/1973    4.575    0.637      NaN
12    9/6/1973      NaN      NaN      NaN
13    9/7/1973    4.945    0.638     2.47
14   9/10/1973    4.985   0.6335     2.44
15   9/10/1973    4.985   0.6335     2.44
16   9/11/1973      NaN   0.6302   2.4875
17   9/12/1973    4.985      NaN   2.3875
18   9/13/1973    5.085    0.645      NaN
19   9/14/1973      NaN   0.6645   2,4975
20   9/15/1973     5.30      NaN    2.500
21   9/16/1973       50    0.700      NaN
22   9/17/1973      NaN      6.5   2.5975
23   9/18/1973    5.16    0.6562   2.4975
24   9/19/1973     5.31  missing    2.495
25   9/20/1973      NaN      NaN      2.5
26  1973-09-21     5.07   0.6465      NaN
27   9/22/1973     5.12      NaN     2.55
28   9/23/1973      NaN    0.652     2.58
29   9/24/1973     5.09   0.6485     2.57
30   9/25/1973      NaN      NaN      NaN
31   9/26/1973     5.13      NaN      2.6
32   9/27/1973      NaN    0.647      NaN
33   9/28/1973      5.1    0.653     2.61
34   9/29/1973      NaN      NaN      NaN
35   9/30/1973      5.2      NaN     2.65
36   10/1/1973      NaN    0.658     2.63
37   10/2/1973     5.16    0.657      NaN
38   10/3/1973  missing    0.656     2.61
39   10/4/1973     5.17      NaN     2.64
40   10/5/1973      NaN    0.661      NaN
41   10/6/1973     5.21    0.662      NaN
42   10/7/1973      NaN      NaN      NaN
43   10/8/1973     5.23    0.664     2.69
44   10/9/1973     5.24      NaN      2.7
45  10/10/1973     5.25    0.666     2.71
46  10/11/1973      NaN    0.667     2.72
47  10/12/1973     5.27      NaN     2.73
48  10/13/1973      NaN    0.669     2.74
49  10/14/1973     5.29     0.67      NaN
50  10/15/1973      NaN    0.671     2.76
51  10/16/1973     5.31      NaN     2.77
52  10/17/1973     5.32    0.673      NaN
53  10/18/1973      NaN    0.674     2.79>

In [14]:
serie = pf['Coffe']
serie

0      0.6735
1         NaN
2       0.658
3      0.6675
4       0.666
5       0.659
6         NaN
7      0.6345
8      0.6387
9         NaN
10     0.6432
11      0.637
12        NaN
13      0.638
14     0.6335
15     0.6335
16     0.6302
17        NaN
18      0.645
19     0.6645
20        NaN
21      0.700
22        6.5
23     0.6562
24    missing
25        NaN
26     0.6465
27        NaN
28      0.652
29     0.6485
30        NaN
31        NaN
32      0.647
33      0.653
34        NaN
35        NaN
36      0.658
37      0.657
38      0.656
39        NaN
40      0.661
41      0.662
42        NaN
43      0.664
44        NaN
45      0.666
46      0.667
47        NaN
48      0.669
49       0.67
50      0.671
51        NaN
52      0.673
53      0.674
Name: Coffe, dtype: str

In [15]:
pf.isnull().sum()

Date      0
Wheat    19
Coffe    17
Corn     15
dtype: int64

In [16]:
pf_deletes = pf.dropna()
pf_deletes

          Date    Wheat    Coffe     Corn
0    8/20/1973    5.085   0.6735    3.115
4    8/24/1973     5.18    0.666      2.9
7    8/29/1973    5.056   0.6345  missing
10    9/4/1973    4.775   0.6432    2.405
13    9/7/1973    4.945    0.638     2.47
14   9/10/1973    4.985   0.6335     2.44
15   9/10/1973    4.985   0.6335     2.44
23   9/18/1973    5.16    0.6562   2.4975
24   9/19/1973     5.31  missing    2.495
29   9/24/1973     5.09   0.6485     2.57
33   9/28/1973      5.1    0.653     2.61
38   10/3/1973  missing    0.656     2.61
43   10/8/1973     5.23    0.664     2.69
45  10/10/1973     5.25    0.666     2.71