In [3]:
import pandas as pd
#diccionario simple pero con datos sucios
data = {"Id_producto": [1011,1002,1003,1003],
        "Cantidad_vendida":[30,None,25,25],
        "Precio":[20.5,15.5,None,22.5]
        }
df = pd.DataFrame(data)
df

   Id_producto  Cantidad_vendida  Precio
0         1011              30.0    20.5
1         1002               NaN    15.5
2         1003              25.0     NaN
3         1003              25.0    22.5

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id_producto       4 non-null      int64
 1   Cantidad_vendida  3 non-null      float64
 2   Precio            3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes

In [ ]:
#para saber numero de valores faltantes por columna
df.isnull().sum()

Id_producto         0
Cantidad_vendida    1
Precio              1
dtype: int64

In [7]:
#eliminar valores no habilitados
df_eliminados = df.dropna()
df_eliminados
#la desventaja es que se borra siempre la fila o registro completo

   Id_producto  Cantidad_vendida  Precio
0         1011              30.0    20.5
3         1003              25.0    22.5

In [5]:
#primero rellena un valor faltante con un valor específico
#posteriormente rellena un valor faltante con el promedio de su columna
valores_nuevos = {"Cantidad_vendida": 0, "Precio":df["Precio"].mean()}
#fillna rellena los valores faltantes con el valor que se le indique
df_rellenados = df.fillna(valores_nuevos)
df_rellenados

   Id_producto  Cantidad_vendida  Precio
0         1011              30.0    20.5
1         1002               0.0    15.5
2         1003              25.0    19.5
3         1003              25.0    22.5

In [ ]:
#cambiar el tipo de datos de una serie
df_rellenados["Cantidad_vendida"] = df_rellenados["Cantidad_vendida"].astype(int)
df_rellenados

   Id_producto  Cantidad_vendida  Precio
0         1011                30    20.5
1         1002                 0    15.5
2         1003                25    19.5
3         1003                25    22.5